In [ ]:
#1. Import numpy as np and see the version (Score 1)
import numpy as np

In [ ]:
#2. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5matrix. (Score:1)
a=np.array([1,2,3,4,5,6,7,8,9,10])
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#3. Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. (Score :2)
a=21
b=[]
for i in range(1,a):
    b.append(i)
print(b)
b=np.array(b)
b=b[4::]
print(b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#4. How to compute the mean, median, standard deviation of a numpy array?Use the array you created above (Score 3)
b_mean = np.mean(b)
print(f"Mean:{b_mean}")
b_median = np.median(b)
print(f"Median:{b_median}")     
b_std = np.std(b)
print(f"Standard Deviation:{b_std}")

Mean:12.5
Median:12.5
Standard Deviation:4.6097722286464435


In [20]:
#5. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y oshape (4,). Subtract y from each row of x using broadcasting. (Score : 2) Note : Score 1
# for timely submission.

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
y = np.array([1, 0, 1, 0])  
result = x - y
print(result)   

[[ 0  2  2  4]
 [ 4  6  6  8]
 [ 8 10 10 12]]
